apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lexigo-gateway
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: lexigo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lexigo-gateway
                port:
                  number: 8080