apiVersion: apps/v1
kind: Deployment
metadata:
  name: lexigo-words
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lexigo-words
  template:
    metadata:
      labels:
        app: lexigo-words
    spec:
      containers:
        - name: words
          image: "{{ .Values.container.image }}:{{ .Values.container.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.words.http.listenPort }}
          envFrom:
            - configMapRef:
                name: lexigo-words-config
          env:
            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: lexigo-secret
                  key: AUTH_SECRET
