apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lexigo-words-db
spec:
  serviceName: "lexigo-words-db"
  replicas: 1
  selector:
    matchLabels:
      app: lexigo-words-db
  template:
    metadata:
      labels:
        app: lexigo-words-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "{{ .Values.words.db.user }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.words.db.password }}"
            - name: POSTGRES_DB
              value: "{{ .Values.words.db.name }}"
          volumeMounts:
            - name: lexigo-words-db-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: lexigo-words-db-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
