apiVersion: v1
kind: Service
metadata:
  name: lexigo-words
  labels:
    app: lexigo-words
spec:
  selector:
    app: lexigo-words
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.words.http.listenPort }}
      targetPort: {{ .Values.words.http.listenPort }}