apiVersion: apps/v1
kind: Deployment
metadata:
  name: lexigo-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lexigo-gateway
  template:
    metadata:
      labels:
        app: lexigo-gateway
    spec:
      containers:
        - name: gateway
          image: lexi-go/gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080