apiVersion: v1
kind: ConfigMap
metadata:
  name: lexigo-image-config
  namespace: lexigo
data:
  HTTP_LISTEN_ADDR: ":8080"
  IMAGE_SERVE_ROOT: "http://lexigo-image:8080"
  IMAGE_MAX_SIZE: "5242880"       
  IMAGE_MAX_WIDTH: "1024"
  IMAGE_MAX_HEIGHT: "1024"