apiVersion: v1
kind: Service
metadata:
  name: lexigo-image
  labels:
    app: lexigo-image
spec:
  selector:
    app: lexigo-image
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080