apiVersion: v1
kind: Service
metadata:
  name: lexigo-gateway
  labels:
    service: lexigo-gateway
spec:
  selector:
    service: lexigo-gateway
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080