apiVersion: apps/v1
kind: Deployment
metadata:
  name: lexigo-words
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lexigo-words
  template:
    metadata:
      labels:
        app: lexigo-words
    spec:
      containers:
        - name: words
          image: lexi-go/words:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080