apiVersion: batch/v1
kind: Job
metadata:
  name: lexigo-words-migrate
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: lexi-go/words-db-migrations:dev
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              value: "postgres://pg-user:pg-pass@lexigo-db:5432/words_db?sslmode=disable"
          command: ["sh", "-c"]
          args: ["migrate -path /migrations -database \"$DATABASE_URL\" up"]