apiVersion: v1
kind: Secret
metadata:
  name: lexigo-auth
  namespace: lexigo
type: Opaque
stringData:
  JWT_ACCESS_SECRET: |-
    {{ .Files.Get (tpl .Values.auth.jwt.access.privateKey .) | nindent 4 }}
  JWT_REFRESH_SECRET: |-
    {{ .Files.Get (tpl .Values.auth.jwt.refresh.key .) | nindent 4 }}
  OAUTH_GOOGLE_CLIENT_ID: "{{ .Values.auth.oauth.google.clientID }}"
  OAUTH_GOOGLE_CLIENT_SECRET: "{{ .Values.auth.oauth.google.clientSecret }}"
