apiVersion: v1
kind: Service
metadata:
  name: lexigo-auth
  labels:
    app: lexigo-auth
spec:
  selector:
    app: lexigo-auth
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080