apiVersion: v1
kind: Secret
metadata:
  name: lexigo-tls
  namespace: lexigo
type: kubernetes.io/tls
stringData:
  tls.crt: |-
    {{ .Files.Get (tpl .Values.tls.cert .) | nindent 4 }}
  tls.key: |-
    {{ .Files.Get (tpl .Values.tls.key .) | nindent 4 }}